# Generated by Django 5.2.1 on 2025-05-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('categoria_vehiculo', models.CharField(max_length=100)),
                ('sucursal_retiro', models.CharField(max_length=100)),
                ('vehiculo_asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(max_length=100)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilapp.alquiler')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alquilapp.paqueteextra')),
            ],
        ),
    ]
