# Generated by Django 5.2.1 on 2025-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('localidad', models.CharField(max_length=100)),
                ('max_pasajeros', models.IntegerField()),
                ('aptitud_discapacidad', models.BooleanField(default=False)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_dias_alquiler', models.IntegerField(default=1)),
            ],
        ),
    ]
