# Generated by Django 5.2.1 on 2025-05-12 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_devolucion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
