# Generated by Django 5.2.1 on 2025-05-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
