# Generated by Django 5.2.1 on 2025-05-11 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilapp', '0002_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='cancelacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquilapp.cancelacion'),
        ),
    ]
